---
title: "Cytoscape_GUI"
author: "Ashfaq Ali"
date: "04/10/2020"
output: html_document
---

##  Learning objectives

In these exercises, we will use the stringApp for Cytoscape to retrieve molecular networks from the STRING database. The exercises will teach you how to:
 - retrieve networks for proteins of interest
 - layout and visually style the resulting networks
 - import external data and map them onto a network
 - perform enrichment analyses and visualize the results
 - merge and compare networks
 - select proteins by attributes
 - identify functional modules through network clustering
 

To follow the exercises, please make sure that you have the latest version of Cytoscape installed. Then start Cytoscape and go to Apps ??? App Manager to check for new apps, install them and update the current ones if necessary. The exercises require you to have certain Cytoscape apps installed. Search for the stringApp in the search field; if it is not already installed, select it and press the Install button to install it. Similarly, make sure you have the yFiles Layout Algorithms, enhancedGraphics, and clusterMaker2 apps installed before closing the App Manager.


Go to the menu File ??? Import ??? Network from Public Databases. In the import dialog, choose STRING: protein query as Data Source and type your favorite protein into the Enter protein names or identifiers field (e.g. SORCS2). You can select the appropriate organism by typing the name (e.g. Homo sapiens). The Maximum number of interactors determines how many interaction partners of your protein(s) of interest will be added to the network. By default, if you enter only one protein name, the resulting network will contain 10 additional interactors. If you enter more than one protein name, the network will contain only the interactions among these proteins, unless you explicitly ask for additional proteins.


2.2. Work with node attributesPermalink

Note that the retrieved network contains a lot of additional information associated with the nodes and edges, such as the protein sequence, tissue expression data, subcellular localization, disease score (Node Table) as well as the confidence scores for the different interaction evidences (Edge Table). In the following, we will explore these data using Cytoscape.

Find the disease score column in the node attributes table (look at the last columns). Sort it by values to see the highest and lowest disease scores. You can highlight the corresponding nodes by selecting the rows in the table, bringing up the context menu (right-click the selected rows) and choosing the Select nodes from selected rows option. You can also use the Fit Selected icon in the menu bar to zoom into the selected node (View ??? Fit Selected).

Give an example for a node with the highest and lowest disease score.

2.4 Continuous color mappingPermalink

Cytoscape allows you to map attributes of the nodes and edges to visual properties such as node color and edge width. Here, we will map the subcellular localization data for nucleus to the node color.

From the left panel side menu, select Style (located underneath Network and above Filter). Click on the ??? button to the right of the property you want to change, in this case Fill Color and set Column to the node column containing the data that you want to use (nucleus). Since this is a numeric value, we will use the Continuous Mapping as the Mapping Type, and set a color gradient for how likely each protein is located in the nucleus. The default Cytoscape yellow???purple color gradient already gives a nice visualization of the confidence of being located in this compartment.

2.5 Select proteins located in the nucleusPermalink

Because many proteins are located in the nucleus, we will identify the proteins with highest confidence of 5. One way to do this is to use the COMPARTMENTS sliders in the STRING Results panel on the right side. Go to the Nodes tab and expand the group of compartments filter by clicking the small triangle. To hide all nodes with a compartment score below 5, find the slider for nucleus and set the low bound to 5.0 by typing the number in the text field and pressing Enter.

Select all remaining nodes in the network view by holding down the modifier key (Shift on Windows, Ctrl or Command on Mac) and then left-clicking and dragging to select multiple nodes. The nodes will turn yellow if they are selected properly. The number of selected nodes is shown in the light grey panel bar on the bottom-right part of the network view panel, just above the Table panel.

How many proteins are found in the nucleus with a confidence of 5? And in mitochondrion?

Important: Move the filter back to 0.0 before continuing with the next exercise.




3.1 Protein network retrievalPermalink

Go to the menu File ??? Import ??? Network from Public Databases. In the import dialog, choose STRING: protein query as the Data Source and paste the list of UniProt accession numbers from the UniProt column in the table into the Enter protein names or identifiers field.

Next, the disambiguation dialog shows all query terms that cannot be matched to a unique STRING protein, with the first matching STRING protein for each query term automatically selected. This default is fine for this exercise; click the Import button to continue. Check that View ??? Always Show Graphics Details for a detailed view of the network.

How many nodes and edges are there in the resulting network? Do the proteins all form a connected network? Why?

Cytoscape provides several visualization options under the Layout menu. Try the Degree Sorted Circle Layout, the Prefuse Force Directed Layout with score as edge weight, and yFiles Organic Layout.

Can you find a layout that allows you to easily recognize patterns in the network? What about the Edge-weighted Spring Embedded Layout with the attribute ???score???, which is the combined STRING interaction score?

3.2 Discrete color mappingPermalink

Cytoscape allows you to map attributes of the nodes and edges to visual properties such as node color and edge width. Here, we will map drug target family data from the Pharos database to the node color. This data is contained in the node attribute called target family.

Select Style from the side menu in the left panel (it is between Network and Filter). Click the ??? button to the right of the property you want to change, in this case Fill Color, and change Column from name to family, which is the node column containing the data that you want to use. The Mapping Type should remain set to Discrete Mapping. This action will remove the rainbow coloring of the nodes and present you with a list of all the different values of the attributes that exist in the network.

Which target families are present in the network?

To color the corresponding proteins, first click the field to the right of an attribute value, i.e. GPCR or Kinase, then click the ??? button and choose a color from the color selection dialog. You can also set a default color, e.g. for all nodes that do not have a target family annotation from Pharos, by clicking on the grey button in the first column of the same row.

How many of the proteins in the network are ion channels or GPCRs?

There are many kinases in the network. We can avoid counting them manually by creating a selection filter in the Filter tab (located underneath Style). Click the ??? button and choose Column filter from the drop-down menu. Then, find and select the attribute Node: family. Write kinase in the text field to select all nodes with this annotation.

How many kinases are in the network?

3.3 Data importPermalink

Network nodes and edges can have additional information associated with them that we can load into Cytoscape and use for visualization. We will import the data from the text file.

To import the node attributes file into Cytoscape, go to File ??? Import ??? Table from File. In the resulting dialog entitled Import Columns From Table, use the drop-down menu next to Where to Import Table Data to choose the option To a Network Collection. Next, change the Key Column for Network from shared name to query term and click OK.

Detailed explanation: Understanding Cytoscape's data import
3.4 Continuous color mappingPermalink

Now, we want to color the nodes according to the quantitative phosphorylation data (log ratios) between disease and healthy tissues for the most significant site for each protein. From the left panel side menu, select Style (it is underneath Network). Then click on the ??? button to the right of the property you want to change, for example Fill Color. Next, set Column to the node column containing the data that you want to use (EOC vs FTE&OSE). Since this is a numeric value, we will use the Continuous Mapping as the Mapping Type, and set a color gradient for how abundant each protein is. The default Cytoscape color gradient blue???white???red already gives a nice visualization of the log ratio.

Are the up-regulated nodes grouped together? Do you see any issues with the color gradient?

To change the colors, double click on the color gradient in order to bring up the Continuous Mapping Editor window and edit the colors for the continuous mapping. In the mapping editor dialog, the color that will be used for the minimum value is on the left, and the maximum is on the right. Double click on the triangles on the top and sides of the gradient to change the colors. The triangles on the top represent the values at which the data will be clipped; anything above the right triangle will be set to the max value. This is useful if you have a small number of values that are significantly higher than the median. As you move the triangles and change the color, the display in the network pane will automatically update ??? this is all easier to do than to explain! If at any point it does not seem to work as expected, it is easiest to just delete the mapping and start again.

Can you improve the color mapping such that it is easier to see which nodes have a log ratio below -4 and above 4?

3.5 Network clusteringPermalink

Next, we will use the MCL algorithm to identify clusters of tightly connected proteins within the network. To do that, press the Cluster network (MCL) button in the STRING Results panel on the right side of the network view. Keep the default granularity parameter (inflation value) set to 4 and click OK to start the clustering. The clusterMaker app will now run the algorithm and automatically create a network showing the clusters.

How many clusters have at least 10 nodes?

We will work with the largest cluster in the network (it should be in the upper left corner). Select the nodes of this cluster by holding down the modifier key (Shift on Windows, Ctrl or Command on Mac) and then left-clicking and dragging to select multiple nodes. The nodes will turn yellow if they are selected properly. Then, create a new network by clicking on the New Network from Selection button and choosing the option From Selected Nodes, All Edges or via the menu item File ??? New Network ??? From Selected Nodes, All Edges.

How many nodes and edges are there in this cluster?

3.6 Functional enrichment and enriched publicationsPermalink

Next, we will retrieve functional enrichment for the proteins in our network of the largest cluster. After making sure that no nodes are selected in the network, go to the menu Apps ??? STRING Enrichment ??? Retrieve functional enrichment or use the Functional Enrichment button in the STRING Panel on the right side. Then, select the original, not clustered network ???String Network??? as Background (instead of ???genome???) and click OK. A new STRING Enrichment tab will appear in the Table Panel on the bottom. It contains a table of enriched terms and corresponding information for each enrichment category. You can see which proteins are annotated with a given term by selecting the term in the STRING Enrichment panel.

Which are the four most statistically significant terms? Hint: Look at the FDR (false discovery rate) value column. Do the UniProt and GO Biological Process terms agree with each other, i.e., annotate the same set of nodes?

Next, we will visualize the top-5 enriched terms in the network using split charts, click the colorful chart icon to show the terms as the charts on the network. You can manually change the layout of the network to improve the visualization. First apply the yFiles Organic Layout and then scale the network to reduce the overlap of the charts using the Layout Tools (Layout ??? Layout Tools).

To save the list of enriched terms and associated p-values as a text file, go to Apps ??? STRING Enrichment ??? Export enrichment results.

To retrieve a list of publications that are enriched for the proteins in the network, go to the menu Apps ??? STRING Enrichment ??? Retrieve enriched publications or press the Enriched Publications button. A new tab called STRING Publications will appear in the Table Panel on the bottom. It contains a table of enriched publications and associated information such as how many of the network proteins were mentioned in each publication.

What is the title of the most recent publication?

3.7 Overlap networksPermalink

Cytoscape provides functionality to merge two or more networks, building either their union, intersection or difference. We will now merge the EOC network we have from the DISEASES query with the one we have from the data, so that we can identify the overlap between them. Use the Merge tool (Tools ??? Merge ??? Networks???) and select the Intersection button. Then, select the two STRING networks from Available Networks list (???String Network - ovary epithelial cancer??? and ???String Network???). Click on > to add them to the list of Networks to Merge and click Merge.

How many nodes are in the intersection?

3.8 Integrate networksPermalink

Now we will make the union of the intersection network, which contains the disease scores, and the experimental network. Use the Merge tool again to make the Union of the merged network and ???String Network???. Make sure that the new merged network has the same number of nodes and edges as ???String Network???, and that some nodes have a disease score (look for the column with this name and sort it by clicking on the column name).

Now, we can change the visualization of the merged network to look like a STRING network and to be able to identify proteins with a high disease score. Specifically, we will change the size of the nodes in function of their disease score. Select Style in the Control Panel and click on the drop-down menu to change the style from default to STRING style v1.5. Then, click on the Lock node width and height option to enable it so that the nodes have only one attribute Size instead of two attributes Height and Width. Modify the values so that by default a node size is 30. To change the default value, you have to click on the default 35.0 value at the left of the Size attribute. Click on the ??? button to add a continuous mapping of the Size attribute using the disease score. The mapping should go from 35 for the lowest disease score to 60 for the highest score. To change the mapping values, first double click on the chart and then double click on the square corresponding to the value you want to modify and set the value you want (35 and 60). Remember to show the graphics details as well as to use a layout that allows you to see all nodes in the network (e.g. yFiles Organic Layout).

Which protein has the highest EOC disease score?

